# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import nlu_pb2 as nlu__pb2


class snips_nluStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.nlu_engine = channel.unary_unary(
        '/snips_nlu/nlu_engine',
        request_serializer=nlu__pb2.nlu_request.SerializeToString,
        response_deserializer=nlu__pb2.nlu_response.FromString,
        )


class snips_nluServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def nlu_engine(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_snips_nluServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'nlu_engine': grpc.unary_unary_rpc_method_handler(
          servicer.nlu_engine,
          request_deserializer=nlu__pb2.nlu_request.FromString,
          response_serializer=nlu__pb2.nlu_response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'snips_nlu', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
