# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nlu.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tnlu.proto\" \n\x0bnlu_request\x12\x11\n\tutterance\x18\x01 \x01(\t\"\x1e\n\x0cnlu_response\x12\x0e\n\x06intent\x18\x01 \x01(\t28\n\tsnips_nlu\x12+\n\nnlu_engine\x12\x0c.nlu_request\x1a\r.nlu_response\"\x00\x62\x06proto3')
)




_NLU_REQUEST = _descriptor.Descriptor(
  name='nlu_request',
  full_name='nlu_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utterance', full_name='nlu_request.utterance', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=45,
)


_NLU_RESPONSE = _descriptor.Descriptor(
  name='nlu_response',
  full_name='nlu_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='intent', full_name='nlu_response.intent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['nlu_request'] = _NLU_REQUEST
DESCRIPTOR.message_types_by_name['nlu_response'] = _NLU_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

nlu_request = _reflection.GeneratedProtocolMessageType('nlu_request', (_message.Message,), dict(
  DESCRIPTOR = _NLU_REQUEST,
  __module__ = 'nlu_pb2'
  # @@protoc_insertion_point(class_scope:nlu_request)
  ))
_sym_db.RegisterMessage(nlu_request)

nlu_response = _reflection.GeneratedProtocolMessageType('nlu_response', (_message.Message,), dict(
  DESCRIPTOR = _NLU_RESPONSE,
  __module__ = 'nlu_pb2'
  # @@protoc_insertion_point(class_scope:nlu_response)
  ))
_sym_db.RegisterMessage(nlu_response)



_SNIPS_NLU = _descriptor.ServiceDescriptor(
  name='snips_nlu',
  full_name='snips_nlu',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=79,
  serialized_end=135,
  methods=[
  _descriptor.MethodDescriptor(
    name='nlu_engine',
    full_name='snips_nlu.nlu_engine',
    index=0,
    containing_service=None,
    input_type=_NLU_REQUEST,
    output_type=_NLU_RESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SNIPS_NLU)

DESCRIPTOR.services_by_name['snips_nlu'] = _SNIPS_NLU

# @@protoc_insertion_point(module_scope)
